services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Koboldsoft\AiReportBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Resources}'

  Koboldsoft\AiReportBundle\Service\OpenAiChatService:
    arguments:
      $openAiApiKey: '%env(OPENAI_API_KEY)%'

